### PR TITLE
Add new members

### PR DESCRIPTION
**Pull request by chrisdickinson**
Hey all — this adds:
- @jasisk 
- @rdodev

### CODE REVIEW

**Comment by benjamingr** [comment]
I'm not on the list before or after the PR, not sure if it matters or anyone cares though :)

**Comment by evanlucas** [comment]
I'm not either :]

**Comment by chrisdickinson** [comment]
Ooh, sorry about that, I'll add you both!

**Comment by chrisdickinson** [comment]
Updated!

**Comment by evanlucas** [comment]
LGTM

**Pull request merged**
