### PR TITLE
correct governance doc copy

### PR DESCRIPTION
**Pull request by estliberitas**
... a bit

### CODE REVIEW

**Comment by benjamingr** [comment]
Looks good to me - don't see why not to merge but I'll let a more experience wg member do the merge in case I'm missing something.

**Comment by eljefedelrodeodeljefe** [comment]
LGTM for this typo /cc @chrisdickinson

**Comment by jasnell** [comment]
LGTM

**Comment by chrisdickinson** [comment]
Thanks! Merging now.

**Pull request merged**
