### PR TITLE
proposal: use hard wrapping for code and soft wrapping for prose

### PR DESCRIPTION
**Pull request by ryansobol**
As a newcomer, I find hard wrapping prose to be extremely annoying and time consuming. I'm eager to hear counter arguments, but IMHO, it seems like a rule that just creates extra work for writers and reviewers.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Consistency > convenience.  The rule in core is 80 columns, the documentation should not be an exception.

**Comment by jasonrhodes** [comment]
When you say "core", you're talking about a rule for code files, right? I've never heard of hard-wrapping paragraphs in markdown—is this already being done like this?

**Comment by bnoordhuis** [comment]
I mean the markdown files here -  https://github.com/nodejs/node/tree/v5.4.0/doc/api - and those are hard-wrapped at 80 columns.  You may find a few lines that are longer if you go looking but those are the exception, not the norm.

**Comment by benjamingr** [comment]
I'm +1 on this, it feels like a very arbitrary limit for doc text.

**Comment by ryansobol** [comment]
> You may find a few lines that are longer if you go looking but those are the exception, not the norm.

While this is true, it demonstrates how inconsistent doc contributions are. Simply put, it's easy to forget to to apply the rule as a writer and check for it as a reviewer. Don't get me wrong, I'm in complete agreement about maintaining consistency of _code_ contributions, no matter if they're in the core or the docs. But I argue that those same rules might not make sense with prose contributions.

**Comment by bnoordhuis** [comment]
I think most of the existing style violations date back from years ago, when reviews were much sloppier than they are today.

**Comment by chrisdickinson** [comment]
I _much_ prefer hard wrapping at 80 since many will be editing the docs in monospace; this should be automatically checked though.

**Comment by Qard** [comment]
-1 In some cases, the place in which the content is being viewed may not provide soft-wrapping and will instead require horizontal scrolling, which is even more annoying, in my opinion.

**Comment by benjamingr** [comment]
> In some cases, the place in which the content is being viewed may not provide soft-wrapping and will instead require horizontal scrolling, which is even more annoying, in my opinion.

Any example for such a place @Qard ?

**Comment by Qard** [comment]
Many command line text editors, github raw view, probably lots of other places.

**Comment by sam-github** [comment]
@Qard command line text editors don't have to wrap if its kept at 80 chars, and github raw view doesn't, either. A number of github tools in fact work quite poorly for text over 90 or a 100 chars, often you can't even see the horizontal scrollbar at the bottom as you stare at the beginning of an unwrapped line.

That's the point of hard wrapping in-source: the author does it, so that all the wide variety of tools that come after do not.

@ryansobol What editor do you use? I'm surprised it won't wrap for you.

**Comment by sam-github** [comment]
And as far as node's source goes: having one rule for markdown and one for all the others is not so handy.

**Comment by evanlucas** [comment]
Yea, I think it should be a hard limit for both code and docs for consistency. -1 from me.

**Comment by RichardLitt** [comment]
> Yea, I think it should be a hard limit for both code and docs for consistency. 

I agree with this. -1. 

What is the procedure in place for coming to consensus on closing (or merging) this PR?

**Comment by eljefedelrodeodeljefe** [comment]
There rather is no process. This can be closed as the majority of contributors is against it.

**Comment by eljefedelrodeodeljefe** [comment]
thanks for the proposal though, Ryan.

**Pull request closed without merging**
