### PR TITLE
Remove style guide (moved to nodejs/node)

### PR DESCRIPTION
**Pull request by gibfahn**
##### Description:

Move the STYLE_GUIDE.md from here to `nodejs/node` (see linked PR: https://github.com/nodejs/node/pull/11321): 

Following discussion in https://github.com/nodejs/node/pull/11286#issuecomment-279200934, I think it makes more sense to have the style guide in the core repo. 

I'm happy to discuss, but we should keep discussion in one PR, so if you have any comments could you make them in https://github.com/nodejs/node/pull/11321 so we can have the discussion in one place?

Also fixes the links in `GETTING-STARTED.md` and `.editorconfig`

### CODE REVIEW

**Review by sam-github — APPROVED** [review]

**Comment by gibfahn** [comment]
The linked PR (https://github.com/nodejs/node/pull/11321) has now landed in node, so unless anyone has any objections we should get this landed.

**Comment by gibfahn** [comment]
Now depends on https://github.com/nodejs/node/pull/11460

**Review by bnoordhuis — APPROVED** [review]

**Review by sam-github — APPROVED** [review]

**Comment by gibfahn** [comment]
@sam-github could you land?

**Comment by sam-github** [comment]
Landed in 7da046d6634e862

@gibfahn do you not have push rights?

**Comment by gibfahn** [comment]
@sam-github no, I'm not a member of the docs team. I would like to be though, not sure what the application process is.

**Comment by addaleax** [comment]
@gibfahn I’ve added you to the team… I personally got added by just requesting it via the github interface, so I think it should be okay?

**Pull request closed without merging**
