### PR TITLE
meta: Add .editorconfig for consistent formatting

### PR DESCRIPTION
**Pull request by drewfish**
The http://editorconfig.org/ project defines a file which can configure various
editors so that they produce documents with consistent formatting.

Some editors need a plugin (http://editorconfig.org/#download) to add support
for this file.

### CODE REVIEW

**Comment by drewfish** [comment]
Only two settings (`indent_style = space` and `indent_size = 2`) were discussed (in PR #9). The others I just choose an initial value so we have a starting point for discussion.

**Comment by chrisdickinson** [comment]
This is great! Would you mind adding a bullet point to the "how we write" section of `GETTING-STARTED.md` that explains that we use editorconfig and links to their site?

**Comment by drewfish** [comment]
updated

**Comment by chrisdickinson** [comment]
LGTM!

**Comment by drewfish** [comment]
Unsure if I should have merged, but a small change, easily undoable if needed :grin:

**Comment by bnb** [comment]
IMO there's not a reason you shouldn't have. :+1:

**Pull request merged**
