### PR TITLE
add building-node-with-ninja.md

### PR DESCRIPTION
**Pull request by Fishrock123**
People always ask me about how to do this, and there's no info about it really anywhere.

R=@nodejs/documentation

### CODE REVIEW

**Comment by Qard** [comment]
Cool, thanks!

Just a note: having the 2 sections covering the 4 steps feels a little weird to me. Reading it from the top down, as someone that hasn't read it before, I can see someone running the quoted steps in the first block and getting frustrated when it doesn't work how they thought it would. Then they'd get to the next block and realize that was the part they actually needed to be reading.

Perhaps it would be better to mix the two blocks together, putting the explanation bits from the first section in with the explicit instructional bits of the second.

**Comment by bengl** [comment]
Closing this since docs aren't intended to live here anymore. Maybe redo the PR against `nodejs/nodejs.org`?

**Comment by Fishrock123** [comment]
note to self: do this

**Comment by chrisdickinson** [comment]
@bengl Ah — I think we're pointing folks at PR'ing this material into nodejs/node itself now (ideally into `doc/guides/`). Although that's not built into the docs output _right now_, it shouldn't be too hard to add!

**Pull request closed without merging**
