### PR TITLE
Add Contributing.md

### PR DESCRIPTION
**Pull request by chrisdickinson**
Our second top-level COMPUTER-YELLING.md document.

Whereas "GUIDE.md" is intended to inform readers about the material we write and our relation to that material, this document is intended to tell readers about the community around this project and their relation to it. As such this addresses various goals the reader might have, such as:
- What to expect when interacting on the tracker,
- How to change things,
- How to join the team,
- How to act as an editor,
- How to merge changes.

Additionally we make it known that by participating in the tracker they are asserting that they are authorized to make contributions, and that they agree to the code of conduct. If they wish to join the team they are informed that they must be exemplars of the values of the community.

Thoughts on this? My specific questions are:
- Are the notes around joining the team clear? The idea is to pair newcomers with existing editors as the project goes on. We're going to be lax about this in the beginning to get off the ground.
- My intent with "one reviewer at a time" is to not overload folks with comments when they submit documentation and make the editing process more conversational. Is this overkill?

### CODE REVIEW

**Comment by Fishrock123** [comment]
I think it has been talked about that Rust's CoC is a little "weak". I'd suggest adopting whatever the Diversity WG adopts (should be soonish I think). Perhaps ok for the interim.

**Comment by chrisdickinson** [comment]
@Fishrock123 Yep, I heard that at Nodeconf as well — the plan is to replace to reflect the larger project's CoC as soon as that's in place. For the time being we're just inheriting what's there so we don't duplicate work.

**Comment by distracteddev** [comment]
LGTM

**Comment by chrisdickinson** [comment]
Merging this now. Thanks all! If there are questions / comments / things you'd like to change, open an issue / PR, or email me (chris at neversaw dot us) if you'd rather discuss them privately.

**Pull request merged**
