### PR TITLE
copyedit

### PR DESCRIPTION
**Pull request by Trott**
Remove comma splice and remove repeated `at this point` phrasing.

### CODE REVIEW

**Comment by Qard** [comment]
"We've now" perhaps?

**Comment by Trott** [comment]
@Qard Sure, that's an improvement. I've updated it with that.

**Comment by bengl** [comment]
Cool. Can you restore the [80 char wrap](https://github.com/nodejs/docs/blob/master/GETTING-STARTED.md#how-we-write)?

**Comment by Trott** [comment]
@bengl 80 char wrap restored

**Comment by bengl** [comment]
LGTM.

@Qard  ?

**Comment by Qard** [comment]
LGTM. :+1:

**Pull request merged**
